### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by dcrockwell** [twincl/fluent#5]
Hello, is this project still active?

**Comment by arthurtw** [comment]
Yes.

**Comment by dcrockwell** [comment]
I claimed the npm package `fluent` because I mistakenly forgot to search for "fluentjs" before claiming the name.

I was going to use it for a library, but since your name is so similar I want to check with you first and give you the option to take ownership of the npm package instead.

**Comment by arthurtw** [comment]
You mean this one? https://www.npmjs.com/package/fluent

It's fine with me to keep using `fluentjs` as my npm package name. Thank you for your kind offer anyway!

**Comment by dcrockwell** [comment]
Sure thing. Are you okay with me using `fluent` for an expressive interface library so long as I put a disclaimer in the README that anybody looking for your project go here?

**Comment by arthurtw** [comment]
That sounds good.
